### ISSUE TITLE
leadership labels

### ISSUE THREAD

**Issue by AllieTaylor** [empirestatehumanevoters/eshv#20]
1. Above the board of director bios, put "Board of Directors"
2. Below all the board members, add section "Advisory Committee"
3. Under the committee add the pics and bios and titles for David, Matt and Gayle:

David Karopkin, Esq. Wildlife Advisor
David is a lifelong Brooklynite and a dedicated advocate for animals and co-existence with wildlife. Among other pursuits, David founded GooseWatch NYC in 2011 and during the past 7 years he has been involved with numerous efforts to protect threatened wildlife living in NYC through activism, legislation and policy. Under his leadership, GooseWatch NYC organized successful campaigns, notably including, the documentation of USDA Wildlife Service round-ups and killing of Canada geese in New York City parks, pivotal in encouraging the City to move towards non-lethal goose management policies, as well as passage of legislation to stop the N.Y.S. Department of Environmental Conservation's plan to eradicate mute swans in New York State, and the prevention of USDA's killing of Staten Island's wild turkeys by helping to coordinate their relocation to farm animal sanctuaries in upstate New York. GooseWatch also worked to protect deer on Staten Island and coyotes in Queens, and participated in the campaign to ban wild animal performances in circuses. As a licensed wildlife rehabilitator, David has assisted with many rescues of injured geese, raccoons, squirrels, and pigeons. David graduated from Brooklyn Law School in 2015, and has served as a Councilmanic Aide for New York City Council Member Daniel Dromm, Legislative Director for New York State Assemblymember Linda B. Rosenthal, and Assistant Law Clerk to the Hon. Justice Katherine A. Levine in the New York State Supreme Court.

![davidkaropkin](https://user-images.githubusercontent.com/28514336/36400103-fb2fddec-159c-11e8-9d6a-258d5fe0ac68.JPG)

Matthew Dominguez, Political Advisor
With nearly a decade of experience fighting for animals, Matthew Dominguez has pioneered legislative and public policy campaigns to protect farmed animals from abuse and to gain fundamental rights for nonhuman animals. He was responsible for passing legislation that outlawed some of the worst factory farming cruelties and leading efforts to defeat over thirty anti-whistleblower “ag-gag” bills during his five-year tenure as Director of Public Policy for Farm Animal Protection at a national animal protection organization. While Director of Public Affairs and Government Relations at the Nonhuman Rights Project, he worked to build an internal infrastructure and operational procedures that would allow NhRP to expand their work into the government relations and public policy arenas. Currently, he is the Managing Director for WildCat Conservation Legal Aid Society who's mission is to end the commercial exploration of all wildcats. Additionally, he holds a full-time job in the private sector in order donate a portion of his salary back to nonprofit organizations who seek to make the world a better place. His work has been covered by the New York Times, Washington Post, CNN, and other major outlets across the country. Matt is a graduate of Lewis and Clark Law School. 
![mattdominguez](https://user-images.githubusercontent.com/28514336/36400258-d2a60e72-159d-11e8-9865-5e949f16f7f0.JPG)

Gayle Boesky, Esq., General Counsel (no bio, no photo yet)

**Comment by staylor** [comment]
this was done
