### ISSUE TITLE
Desktop sub-nav doing weird things

### ISSUE THREAD

**Issue by michellevfar** [empirestatehumanevoters/eshv#21]
On desktop - click around all of the sub-nav items.
Not anchoring to correct section and then bouncing around to different spots.
Please test

**Comment by staylor** [comment]
![screen shot 2018-02-21 at 9 56 51 pm](https://user-images.githubusercontent.com/52932/36517902-29157d1e-1752-11e8-95a0-d35fd05bb7f6.png)

one of the issues is the content at the bottom of some of these. there isn't enough space to keep scrolling past the footer. if the content had a couple of paragraphs, it would make more sense when the page scrolls it.

**Comment by staylor** [comment]
I made changes and commented on Feb 21, no reply
