### ISSUE TITLE
Mobile sub-nav needs fixing and testing

### ISSUE THREAD

**Issue by michellevfar** [empirestatehumanevoters/eshv#22]
1) mobile sub-nave should have the little arrow to expand and collapse the different sections. Right now when you click on menu burger, all main nav AND sub-navs are visible. See VolotLatino on mobile. I have a bunch of other examples if you need them

2) Click on mobile nav/sub-nav - just not working correctly in a few ways. I can detail if you need me to, but it should be obvious if you tool around

3) Check where sub-nav items anchor to. Click on 'OUR TEAM' - should anchor to the text that says "Board of Directors' or 'Our Team'. Now it anchors to Allie's photo. If you click on 'Our Focus" it anchors to animal icon - should anchor so that you see the text 'Our Focus'

4) do testing

**Comment by michellevfar** [comment]
@staylor are you working on this this weekend? And other remaining issues?

**Comment by staylor** [comment]
1. done
2. what does this mean?
3. I am playing around with the scroll offset on click, will try to tighten this up as best as possible

**Comment by staylor** [comment]
I commented on Feb 25, no reply
