### ISSUE TITLE
Desktop 'Our Team'

### ISSUE THREAD

**Issue by michellevfar** [empirestatehumanevoters/eshv#23]
**1) Desktop Bios should be in 4 columns on desktop. Can you force to always be in 4?**
![about us 5 columns](https://user-images.githubusercontent.com/36522941/36458620-c03a63d8-167d-11e8-8ccf-a8397f635346.png)

2) reduce some space between "Our Team" subhead and "BOARD OF DIRECTORS" subhead. Looks too spread out. Also between 'BOD' subhead and photos. Also between 'Advisory Committee' subhead and photos.

3) Circle arrow should be white, not the transparent blue. See original file I sent. Here's reference
![bio desktop ref](https://user-images.githubusercontent.com/36522941/36458698-2d4da746-167e-11e8-9aa3-06818ce5fbca.png)

4) on Board pop-up bios, make spacing consistent between names and bio text - so mine should match Allie's, Jabari's should match everyone elses. 

5) On pop-up window names/title look tight. Needs a little more line spacing. For example, if you look at Joyce, the y and i are overlapping. Loosen - but just a bit overall.
Same line spacing comment between last names and title. Looks tight.
-- OR -- for all pop-ups, names can be in one line

7) For Pop-up names/title - make them blue like on main page

8) For Pop-up names/title - use same font weights as on main page

8) For Pop-up bio text - is the text black or grey? Should be grey, if it's not already

**Comment by staylor** [comment]
did these
