### ISSUE TITLE
Mobile 'Our Team'

### ISSUE THREAD

**Issue by michellevfar** [empirestatehumanevoters/eshv#24]
****1) Mobile version should be in 2 columns.** Match size and spacing of VotoLatino**

![vl mobile board](https://user-images.githubusercontent.com/36522941/36459148-9d0df2fa-1680-11e8-8968-0b50d0e57d43.jpg)

**2) Match space between columns and match margins to VL.** Also match spacing above each person - should be a little bit more space between people. Right now there is equal space above and below names. *Don't change space above names. Add - a little bit - below names. Compare below to VL:

![vfar board spacing](https://user-images.githubusercontent.com/36522941/36459266-13c9e3e0-1681-11e8-840a-2b54d6d07bc3.jpg)

3) Mobile bio photos should have circle arrow, in white, to prompt clicking. Image doesn't have to change to blue, but should have circle arrow

4) Same comments as in Desktop regarding tothe pop-up names/titles. Should blue, loosen up and can be in one line

**Comment by staylor** [comment]
did these

**Comment by staylor** [comment]
did this on Feb 21
