### ISSUE TITLE
Headshot sizes - fix Matt/David

### ISSUE THREAD

**Issue by michellevfar** [empirestatehumanevoters/eshv#28]
All bio photos should have the same approximate cropping. So, Matt and David should match our heads - right now they are too small. This goes for anyone else we ads to the site. We might get photos in all different sizes, but they should be made consistent with others
If you need me to resize and send new jpegs let me know.

![headshot size](https://user-images.githubusercontent.com/36522941/36460555-e4b6374c-1686-11e8-8d02-0207bbd3900b.png)

**Comment by staylor** [comment]
done + added Chelsie
