### ISSUE TITLE
JOIN US & DONATE buttons

### ISSUE THREAD

**Issue by michellevfar** [empirestatehumanevoters/eshv#29]
On eshv site, the JOIN US & DONATE buttons were sticky at the top.
Was this intentionally changed?

![join donate buttons](https://user-images.githubusercontent.com/36522941/36460687-83f92814-1687-11e8-901a-05ed1178de74.jpg)

**Comment by AllieTaylor** [comment]
Old site forwards to vfar

**Comment by michellevfar** [comment]
@AllieTaylor did you close this because you do not want 'join us' 'donate' buttons at the top anymore?
