### ISSUE TITLE
Sub-nav - better position?

### ISSUE THREAD

**Issue by michellevfar** [empirestatehumanevoters/eshv#30]
Is there a way to move sub-nav items closer to their nav parent? They are so far away now that it's a bit much to keep nav item selected while moving cursor over to select sub-nav.  I assume they are all the way to the left as they are lining up with the page margin on the left.  Is there another, better option? 
Can sub-nav center under the main nav, so it's closer?

![screen shot 2018-02-20 at 9 49 53 pm](https://user-images.githubusercontent.com/36522941/36460911-b449d3b4-1688-11e8-9271-370e3deaba6a.png)

![screen shot 2018-02-20 at 9 50 11 pm](https://user-images.githubusercontent.com/36522941/36460917-bc6d5926-1688-11e8-82f2-657fe7a31db0.png)

**Comment by staylor** [comment]
centered it, works better
