### ISSUE TITLE
Change 'What We Do' text size - asap

### ISSUE THREAD

**Issue by michellevfar** [empirestatehumanevoters/eshv#31]
**Please do the following ASAP.**
Change the p style of the text in "WHAT WE DO" section to match size of our bios.
So, basically - smaller - so that page doesn't scroll forever until we can fix the whole design of that page.
Match bio text size and line height.
Change the subheads to blue.

**Comment by staylor** [comment]
done

**Comment by staylor** [comment]
this was done the day you asked
